### ISSUE TITLE
请问还有相关的重构练习吗

### ISSUE THREAD

**Issue by HealerOS** [linesh-simplicity/calisthenics#18]
我只找到gitbook 1 2 4 的题目。2和4还是在你的仓库找到的。 原仓库好像删掉了，第三题：bug zero 找不到了，请问你是在哪里找到的重构练习题目呀
<img width="294" alt="image" src="https://github.com/EthanLin-TWer/calisthenics/assets/71708873/f9fafe4b-350a-4928-95fa-618c63a0d180">

**Comment by EthanLin-TWer** [comment]
抱歉，很晚才看到。Bug Zero这个练习我看我的仓库里还是放着的，你可以看看（不过时间过去很久了不知道你还需要不）：

* JavaScript：https://github.com/EthanLin-TWer/bugszero
* Java：https://github.com/EthanLin-TWer/bugszero-java

**Comment by HealerOS** [comment]
> 抱歉，很晚才看到。Bug Zero这个练习我看我的仓库里还是放着的，你可以看看（不过时间过去很久了不知道你还需要不）：
> 
> * JavaScript：https://github.com/EthanLin-TWer/bugszero
> * Java：https://github.com/EthanLin-TWer/bugszero-java

不用了 很感谢
